Repository safaama1/Advanced-Final-Project, pull requests merged in 2021-09, with the labels that each got.

#29 added parse bills to database
  models/Bill.js
  models/User.js
  package-lock.json
  package.json
  routes/room.js
  services/Bill.js
  services/users.js
  static-assets/js/imageToText.js
Labels: enhancement

#30 Add romm page HB & fix redirect problem in router
  routes/room.js
  server.js
  static-assets/css/invoice.css
  static-assets/js/imageToText.js
  views/layouts/billPage.hbs
  views/main.hbs
Labels: documentation, enhancement, fix

#31 user can now join other users and view thier rooms
  package-lock.json
  package.json
  pages/joinRoom.html
  pages/signup.html
  routes/account.js
  routes/room.js
  server.js
  services/Bill.js
  services/users.js
  static-assets/js/imageToText.js
  views/main.hbs
Labels: documentation, enhancement, fix

#32 edit the bill page total price & loading animation
  package.json
  pages/profile.html
  routes/room.js
  server.js
  static-assets/css/invoice.css
  static-assets/css/profile.css
  static-assets/js/imageToText.js
  static-assets/js/utility.js
  views/layouts/billPage.hbs
  views/main.hbs
Labels: documentation, enhancement

#33 multiple users can now pick the items they bought in the same room
  server.js
  views/main.hbs
Labels: enhancement

#34 added css html js for about us page
  pages/aboutUs.html
  pages/main.html
  pages/profile.html
  server.js
  static-assets/css/aboutUs.css
Labels: enhancement

#35 Add env variables to the mongo connection & created cluster
  package-lock.json
  package.json
  server.js
Labels: enhancement

#36 added passwords must be 8 or more charachters
  pages/signup.html
  routes/account.js
Labels: enhancement

#37 Fixed the paths of login & signup
  pages/signup.html
  routes/account.js
Labels: fix

#38 Fix css paths
  pages/joinRoom.html
  pages/logIn.html
  pages/signup.html
Labels: fix

#39 Update ReadMe file
  README.md
Labels: documentation
