Repository safaama1/Advanced-Final-Project, pull requests merged in 2021-08, with the labels that each got.

#2 configured docker and mongoDB and created the user model
  docker-compose.yml
  models/User.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#3 added the sign up page
  SignUp.html
  server.js
  static-assets/css/SignUp.css
Labels: enhancement

#4 fixed the main.html
  main.html
  server.js
Labels: bug

#5 added login page & buttons paths
  SignUp.html
  logIn.html
  main.html
  server.js
  static-assets/css/logIn.css
  static-assets/js/main-menu.js
Labels: documentation, enhancement

#6 added class UserService
  server.js
  services/users.js
Labels: enhancement

#7 added signup and login funcionality
  SignUp.html
  package-lock.json
  package.json
  pages/logIn.html
  pages/main.html
  pages/profile.html
  pages/signup.html
  routes/account.js
  server.js
Labels: documentation

#8 Allow access to user info from html
  pages/profile.html
  routes/account.js
  static-assets/js/utility.js
Labels: enhancement

#9 Added Profile Page (HTML & CSS)
  models/User.js
  pages/profile.html
  pages/signup.html
  routes/account.js
  server.js
  static-assets/css/profile.css
  static-assets/images/pic2.jpg
  static-assets/images/pic3.jpg
  static-assets/images/pic4.jpg
  static-assets/images/pic5.jpg
  static-assets/images/pic6.jpg
  static-assets/js/profile.js
  static-assets/js/utility.js
Labels: bug, enhancement

#10 Fixed some bugs & Added scan options
  pages/logIn.html
  pages/profile.html
  routes/account.js
  static-assets/css/logIn.css
  static-assets/css/profile.css
  static-assets/js/drop-down.js
Labels: bug, documentation, enhancement

#11 added getFile from user functionality
  pages/profile.html
  static-assets/css/profile.css
  static-assets/js/drop-down.js
  static-assets/js/utility.js
Labels: enhancement

#12 user can now upload photos and their content will be converted to text
  .eslintrc.json
  pages/profile.html
  static-assets/js/imageToText.js
Labels: enhancement

#17 add bill model and bill services
  models/Bill.js
  models/User.js
  services/Bill.js
  services/users.js
  static-assets/js/imageToText.js
Labels: enhancement

#27 add handlebars & temp invoice page
  package-lock.json
  package.json
  routes/room.js
  server.js
  static-assets/css/SignUp.css
  static-assets/css/main.css
  static-assets/css/profile.css
  views/layouts/billPage.hbs
  views/main.hbs
Labels: documentation, enhancement
